### ISSUE TITLE
feat: rename/alias to add-dep

### ISSUE THREAD

**Issue by AndersDJohnson** [arfeo/npm-add-dependencies#11]
## Expected Behavior
Would be nice to have a more terse command like `npx add-dep` or `npx add-deps`. We could rename/publish as `add-dep` / `add-deps` instead.

## Actual Behavior
Must run as `npx npm-add-dependencies` which takes long to type out.

**Comment by arfeo** [comment]
I definitely like the idea.

**Comment by arfeo** [comment]
There was no way to create `add-dep` package since `npm` throws 

> npm ERR! Package name too similar to existing packages

So, I've published https://www.npmjs.com/package/add-dependencies. It's four chars less now! =) Hope this could help. =)

**Comment by AndersDJohnson** [comment]
@arfeo That's too bad. But `add-dependencies` is better, thanks!
