### ISSUE TITLE
feat: support --save-exact

### ISSUE THREAD

**Issue by AndersDJohnson** [arfeo/npm-add-dependencies#13]
## Expected Behavior
We should support `--save-exact`/`-E` to write the exact version `X.X.X` instead of `^X.X.X`.

## Actual Behavior
No way to do this right now.

**Comment by arfeo** [comment]
It is possible via `@x.x.x`. E.g.,

```sh
$ npm-add-dependencies react@16.8.0
```

**Comment by AndersDJohnson** [comment]
@arfeo Sure, that works. Closing.

**Comment by AndersDJohnson** [comment]
@arfeo Though I suppose that requires the user to know the exact current version, whereas `--save-exact`/`-E` would determine it automatically.

Also found that `yarn` has an `--exact` alias and also a `--tilde`/`-T` option to use `~`.
