### ISSUE TITLE
fix: bundledDependencies should be array

### ISSUE THREAD

**Issue by AndersDJohnson** [arfeo/npm-add-dependencies#14]
## Expected Behavior
With `--bundled`, we're supposed to get `bundledDependencies` as an array, not an object (see [here for npm](http://npm.github.io/using-pkgs-docs/package-json/types/bundleddependencies.html) and [here for yarn](https://yarnpkg.com/lang/en/docs/dependency-types/#toc-bundleddependencies)).

Per `npm` docs:
```
-B, --save-bundle: Saved dependencies will also be added to your bundleDependencies list.
```

So we should get:
```
  "bundledDependencies": ["debug"]
```

So perhaps we should remove support for it, or implement it correctly?

## Actual Behavior
```
  "bundledDependencies": {
    "debug": "^4.1.1"
  }
```

## Steps to Reproduce the Problem

  1. `npx npm-add-dependencies --bundled debug`

**Comment by arfeo** [comment]
Thanks for catching this. I think, we'd better remove `--bundled` flag support.

**Comment by arfeo** [comment]
@AndersDJohnson Could you do this by yourself?
