### ISSUE TITLE
refactor: use 3rd party args parser

### ISSUE THREAD

**Issue by AndersDJohnson** [arfeo/npm-add-dependencies#16]
We should refactor to use a 3rd party args parser like `yargs` for simpler and less error-prone code.

**Comment by arfeo** [comment]
`yargs` is very good indeed, but it is too heavy for a lightweight script like `npm-add-dependencies`, I think. Is there any bug in args parsing that you've catched?

**Comment by AndersDJohnson** [comment]
@arfeo It's fine for now but we may wish to continue adding more features to get to parity with `npm`/`yarn` `install`/`add` in which case `yargs` could simplify. We can keep this one open until then, or just close for now.
