### ISSUE TITLE
Cannot add dependencies starting with @ any more

### ISSUE THREAD

**Issue by cdipiet** [arfeo/npm-add-dependencies#6]
## Expected Behavior
npm-add-dependencies @angular/material
ok

## Actual Behavior
npm-add-dependencies @angular/material
This script adds dependencies (latest or specified versions) into the package.json file without installing them

Adding packages to 'dependencies'...
undefined:2
versions@0.3.0 | MIT | deps: 8 | versions: 17
^

SyntaxError: Unexpected token n JSON at position 1
    at JSON.parse (<anonymous>)
    at npmRun.exec (C:\Users\c383650\AppData\Roaming\npm\node_modules\npm-add-dependencies\index.js:69:42)
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

## Steps to Reproduce the Problem

  1. Try to add any dependency whose name starts with @, example: npm-add-dependencies @angular/material

## Specifications

  - Version: 0.2.0
  - Platform: Windows, Linux
  - Subsystem:

Hello, on rorw 59 of index.js i found:
runNpmShow(dep) {
  const [depName, depVersion] = dep.split('@');

such split cause an undefined depName when package name starts with @

**Comment by arfeo** [comment]
Hi, I am sorry for that. Please, use version 0.1.5 now. I will push fixes in a day. Thanks.

**Comment by arfeo** [comment]
Fixed in version 0.2.1

**Comment by cdipiet** [comment]
Thank you so much, it's working perfectly now!
